### ISSUE TITLE
Anonymous login with ejabberd tries "plain" auth first and fails

### ISSUE THREAD

**Issue by poVoq** [nioc/xmpp-web#101]
### Describe the bug

When running this with ejabberd anonymous auth it fails to login as it tries "plain" auth first and that obviously fails.

Only by explicitly forbidding "plain" auth ejabberd side anonymous auth works. This needs to be added:

```
host_config:
  anon.example.org:
    auth_method: [anonymous]
    disable_sasl_mechanisms: [ "X-OAUTH2", "digest-md5" , "plain" ]
    anonymous_protocol: sasl_anon
```

without the `disable_sasl_mechanisms` part it doesn't work.

I am also seeing a problem with room discovery on the `#/guest/rooms` url, but I am still investigating what the cause might be.

### Expected behavior

As far as I know sasl_anon should work as is and not require such workarounds.

### XMPP-web version

0.10.0

### Installation

Github release archive

### XMPP server(s)

ejabberd

**Comment by poVoq** [comment]
Not directly related, but I made room discovery work in ejabberd by explicitly adding the muc domain to mod_disco for the anonymous vhost like this:

```
host_config:
  anon.example.org:
    auth_method: [anonymous]
    disable_sasl_mechanisms: [ "X-OAUTH2", "digest-md5" , "plain" ]
    anonymous_protocol: sasl_anon
    modules:
      mod_disco:
        extra_domains:
          - "muc.example.org"
```

Not sure if this needs a fix xmpp-web side, but might be nice to add to the docu.
