### ISSUE TITLE
Can not upload file when server use a component (domain do not advertise feature)

### ISSUE THREAD

**Issue by vladosam** [nioc/xmpp-web#58]
**Describe the bug**
I can't send files because there is no paperclip icon. If i use gajim I can send files to my ejabberd server. 
This is my docker-compose.yaml
```
version: "3.4"
services:
  xmpp-web:
    image: nioc/xmpp-web:latest
    ports:
      - "8080:80"
    environment:
      - XMPP_WS=https://myserver.com:5443/ws
      - APP_DEFAULT_DOMAIN=myserver.com
      - APP_WS=wss://myserver.com:5443/ws
```
**Expected behavior**
To see paperclip icon

**Screenshots**
![Screenshot from 2022-06-01 13-36-25](https://user-images.githubusercontent.com/8487479/171395753-38738a5f-2177-4fcd-b8a7-356a6a6420b0.png)

**Application (please complete the following information):**
 - Version 0.9.2
 - XMPP Server: Ejabberd-21.12

**Browser (please complete the following information):**
 - Device: desktop
 - OS: Linux
 - Browser Firefox
